# Generated by Django 4.1.7 on 2023-03-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoining',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employees',
            name='Department',
            field=models.CharField(max_length=500),
        ),
    ]
